### ISSUE TITLE
Feature Request: Support for Spring Boot Admin Server 2.1.6

### ISSUE THREAD

**Issue by pixtim** [slydeveloper/spring-boot-admin-docker#1]
I've encountered a bug in Spring Boot Admin Server 2.0.1 that freezes the browser and OS when opening the "HTTP Traces" tab. Would it be possible to upgrade the docker image with Spring Boot Admin Server 2.1.6?

**Comment by slydeveloper** [comment]
Fixed, now based on Spring Boot Admin 2.1.6. Docker image versions: latest,1.1

**Comment by pixtim** [comment]
Thanks @slydeveloper !

**Comment by slydeveloper** [comment]
> Thanks @slydeveloper !

NP. Let me know if faced any issues.
